version: '3.8'

services:
  web-prompts:
    build: .
    container_name: web-prompts-app
    ports:
      - "5045:5045"
    volumes:
      # Монтируем папку instance для сохранения базы данных
      - ./instance:/app/instance
      # Монтируем папку config для возможности изменения конфигурации
      - ./config:/app/config:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/api/technologies')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - web-prompts-network

networks:
  web-prompts-network:
    driver: bridge 